/**
 * Handles errors generated by controllers
 * 
 * @param event The event generated by the Event Handler
 * @param error The error
 * @returns The error message, if any
 */
export default function (event: any, error: any): { message?: any } {
    setResponseStatus(event, error.number ?? 500);

    return { message: error.content != undefined ? error.content : error };
}